in ../builtins.maude
in ../lambda-syntax.maude

in lambda-semantics-bigstep.maude

in ../lambda-programs.maude

mod TEST is including LAMBDA-SEMANTICS-BIGSTEP + LAMBDA-PROGRAMS .  endm

set print with parentheses on .

parse x .
parse 0' .
parse succ(0') .
parse zero?(x) .
parse zero?(succ(0')) .
parse /\ x : nat . x .
parse nonZeroVal(succ(0')) .
parse (mZeroer) 0' .
parse mCombinator .
parse (trueL) 0' succ(0') .

q .